#version: '3.8'
#services:
#  mongo:
#    image: mongo:latest
#    container_name: mongo
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo-data:/data/db
#
#  mongo-express:
#    image: mongo-express
#    ports:
#      - "8081:8081"
#    environment:
#      #- ME_CONFIG_MONGODB_SERVER=admin
##      - ME_CONFIG_BASICAUTH_USERNAME=xyz8888
##      - ME_CONFIG_BASICAUTH_PASSWORD=guazi1234
#      - ME_CONFIG_MONGODB_SERVER=host.docker.internal
#      - ME_CONFIG_MONGODB_PORT=27017
#      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=xyz8888
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=guazi1234
#      - ME_CONFIG_BASICAUTH_USERNAME=admin
#      - ME_CONFIG_BASICAUTH_PASSWORD=admin
#
#volumes:
#  mongo-data:
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network


  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mongo-data: